apiVersion: v1
kind: Service
metadata:
  name: {{ include "sensu-go-sandbox.fullname" . }}
  labels:
    {{- include "sensu-go-sandbox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api-listen-port
      protocol: TCP
      name: api-listen-port
  selector:
    {{- include "sensu-go-sandbox.selectorLabels" . | nindent 4 }}
